version: "3.7"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    command: npm run dev:backend
    restart: on-failure
    volumes:
      - ${PWD}/data/lnd:/data/.lnd
      - ${PWD}/statuses:/statuses
    environment:
      PORT: "3006"
      BITCOIN_HOST: "bitcoind"
      RPC_PORT: "18443"
      RPC_USER: "umbrel"
      RPC_PASSWORD: "2hmQlIgYfjFoMGAwBQPdvpJ6vDuQbOoBfG_LxznanAk="
      LND_NETWORK: "regtest"
      LND_HOST: "lnd"
      LND_REST_HIDDEN_SERVICE_FILE: "/var/lib/tor/lnd-rest/hostname"
      LND_GRPC_HIDDEN_SERVICE_FILE: "/var/lib/tor/lnd-grpc/hostname"
      TLS_FILE: "/data/.lnd/tls.cert"
      MACAROON_DIR: /data/.lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/
      DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://umbrel.local"}
    ports:
      - "3006:3006"
  lnd:
    image: lightninglabs/lnd:v0.14.1-beta@sha256:810f290f4da51adaf57d53bc1f1e65b52b03c543f322da0b98fb8c47be94a27a
    user: 1000:1000
    volumes:
      - ${PWD}/data/lnd:/data/.lnd
    environment:
      HOME: /data
    restart: on-failure
    external_links:
      - bitcoind:bitcoind
    ports:
      - "10009:10009"

networks:
  default:
    name: umbrel_main_network
    ipam:
      driver: default
      config:
        - subnet: "10.21.21.0/24" # NETWORK_IP
